# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Workflow syntax reference:
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Deploy

on:
  release:
    types: [published]

env:
  # This is used by the SharedProps to detect a PR build
  APP_NAME: release
  AWS_REGION: us-east-2
  APP_PACKAGE_NAME: '@pwrdrvr/microapps-app-release'

jobs:
  version:
    if: startsWith( github.ref, 'refs/tags/release/')
    runs-on: ubuntu-latest
    outputs:
      packageVersion: ${{ steps.packageVersion.outputs.packageVersion }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Apply Version from Git Tag
        run: |
          npm version from-git --no-git-tag-version --workspaces

      - name: Extract Current NPM Version
        id: packageVersion
        run: |
          echo 'PACKAGE_VERSION='$(node -p -e "require('./package.json').version") >> $GITHUB_ENV
          echo "::set-output name=packageVersion::${packageVersion}"

      - name: Create version.txt
        run: echo ${PACKAGE_VERSION} > version.txt

      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: version-txt
          path: version.txt

  build:
    if: startsWith( github.ref, 'refs/tags/release/')
    needs:
      - version
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Node Modules
        run: npm ci

      - name: Link to node_modules - App
        working-directory: packages/app/node_modules/.bin
        run: |
          ln -s ../../../../node_modules/.bin/next

      # Fixes errors due to JSII tsconfig.json not ignoring libs
      # node_modules/flatpickr/dist/types/instance.d.ts(37,21): error TS2304: Cannot find name 'Node'.
      # Error: node_modules/flatpickr/dist/types/instance.d.ts(82,56): error TS2304: Cannot find name 'HTMLElementTagNameMap'.
      # Error: node_modules/@types/carbon-components-react/lib/components/FileUploader/FileUploaderDropContainer.d.ts(46,80): error TS2304: Cannot find name 'File'.
      # Error: node_modules/@types/overlayscrollbars/index.d.ts(348,19): error TS2304: Cannot find name 'NodeListOf'.
      - name: Modify cdk-construct tsconfig.json
        run: |
          mv ./packages/cdk-construct/tsconfig.json ./packages/cdk-construct/tsconfig.jsii.json
          jq ".compilerOptions += { \"skipLibCheck\": true }" ./packages/cdk-construct/tsconfig.jsii.json > ./packages/cdk-construct/tsconfig.json

      - name: Build All TypeScript
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Download Artifact - Version.txt
        uses: actions/download-artifact@v2
        with:
          name: version-txt
      - run: echo PACKAGE_VERSION=$(cat version.txt) >> $GITHUB_ENV

      - name: Apply NPM Version
        run: |
          npm version ${PACKAGE_VERSION} --no-git-tag-version --workspaces

      - name: Apply Next.js Version
        run: |
          npx -w ${APP_PACKAGE_NAME} microapps-publish nextjs-version -n ${PACKAGE_VERSION}

      - name: Build Next.js App
        run: |
          npm run build:next
      
      - name: Build Entry for App
        run: |
          npm run build:entry

      - name: Install Next.js for Rollup
        working-directory: packages/app-entry/runtime-deps/
        run: |
          npm ci --omit=dev

      - name: Combine Build Outputs
        run: |
          rm -rf ./packages/app/.next/cache
          mkdir -p ./packages/cdk-construct/lib/microapps-app-release
          mv ./packages/app/.next/serverless ./packages/app/.next/server
          cp -R ./packages/app/.next ./packages/cdk-construct/lib/microapps-app-release
          cp -R ./packages/app-entry/runtime-deps/node_modules ./packages/cdk-construct/lib/microapps-app-release

      # Upload Artifact
      - name: Zip Package
        working-directory: packages/cdk-construct/lib/
        run: zip -r nextjs.zip microapps-app-release
      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          name: app_zip
          path: packages/cdk-construct/lib/nextjs.zip

  build-storybook:
    if: startsWith( github.ref, 'refs/tags/release/')
    needs:
      - version
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Node Modules
        run: npm ci
      
      - name: Download Artifact - Version.txt
        uses: actions/download-artifact@v2
        with:
          name: version-txt
      - run: echo PACKAGE_VERSION=$(cat version.txt) >> $GITHUB_ENV

      - name: Apply NPM Version
        run: |
          npm version ${PACKAGE_VERSION} --no-git-tag-version --workspaces

      - name: Build Story Book
        run: |
          npm run -w ${APP_PACKAGE_NAME} build:storybook

      # Upload Artifact
      - name: Zip Package
        working-directory: packages/app/
        run: zip -r storybook-static.zip storybook-static
      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          name: storybook_zip
          path: packages/app/storybook-static.zip

  deploy-ghpublic:
    needs:
      - version
      - build
      - build-storybook
    # Limit concurrency to 1, with queueing, per workflow
    # Limit concurrency to 1, with queueing, per workflow per PR
    concurrency:
      group: deploy-ghpublic-${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: ghpublic
      url: https://apps.ghpublic.pwrdrvr.com/${{ env.APP_NAME }}/${{ needs.version.outputs.packageVersion }}
    env:
      ENV: prod
      DEPLOYER_LAMBDA_NAME: microapps-core-ghpublic-deployer-prod
      CDK_CONTEXT_ARGS: "--context @pwrdrvr/microapps:tableName=microapps-core-ghpublic-prod --context @pwrdrvr/microapps:s3BucketName=com.pwrdrvr.ghpublic.apps"
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Node Modules
        run: npm ci

      - name: Download Artifact - App
        uses: actions/download-artifact@v2
        with:
          name: app_zip
          path: packages/cdk-construct/lib/
      - name: Unzip Artifact - App
        working-directory: packages/cdk-construct/lib/
        run: unzip nextjs.zip

      # Prevent the static files from getting pulled into the Lambda
      - name: Remove Static Files from App Build
        working-directory: packages/cdk-construct/lib/
        run: |
          mkdir .static_files
          mv microapps-app-release/.next/static .static_files

      # Move to .mjs so it's treated as as module even though package.json will
      # have type=commonjs
      # - name: Move index.js to index.mjs
      #   working-directory: packages/cdk-construct/lib/microapps-app-release/
      #   run: |
      #     mv ./index.js ./index.mjs

      - name: Download Artifact - Story Book
        uses: actions/download-artifact@v2
        with:
          name: storybook_zip
          path: packages/app/
      - name: Unzip Artifact - App
        working-directory: packages/app/
        run: unzip storybook-static.zip

      - name: Download Artifact - Version.txt
        uses: actions/download-artifact@v2
        with:
          name: version-txt
      - run: echo PACKAGE_VERSION=$(cat version.txt) >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: microapps-app-${{ env.APP_NAME }}-build
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/builder-writeRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Preflight Check Version - App
        run: |
          npx microapps-publish preflight -a ${APP_NAME} -n ${PACKAGE_VERSION} -d ${DEPLOYER_LAMBDA_NAME}

      - name: Preflight Check Version - Story Book
        run: |
          npx microapps-publish preflight -a ${APP_NAME}-storybook -n ${PACKAGE_VERSION} -d ${DEPLOYER_LAMBDA_NAME}

      - name: Deploy CDK Stack - App
        run: npx cdk deploy ${CDK_CONTEXT_ARGS} --hotswap --require-approval never app

      - name: Publish to MicroApps - App
        run: |
          npx microapps-publish publish -a ${APP_NAME} -n ${PACKAGE_VERSION} -d ${DEPLOYER_LAMBDA_NAME} -l microapps-app-${APP_NAME}-${ENV} -s packages/cdk-construct/lib/.static_files/static

      - name: Publish MicroApps - Story Book
        run: |
          npx microapps-publish publish-static -a ${APP_NAME}-storybook -n ${PACKAGE_VERSION} -d ${DEPLOYER_LAMBDA_NAME} -s packages/app/storybook-static -i index.html

  deploy-pwrdrvr:
    needs:
      - version
      - deploy-ghpublic
    strategy:
      matrix:
        env:
          - dev
          - qa
          - prod
    # Limit concurrency to 1, with queueing, per workflow
    # Limit concurrency to 1, with queueing, per workflow per PR
    concurrency:
      group: deploy-${{ matrix.env }}-${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.env }}
      url: https://apps.${{ steps.getDomainInfix.outputs.domainInfix }}pwrdrvr.com/${{ env.APP_NAME }}/${{ needs.version.outputs.packageVersion }}
    env:
      ENV: ${{ matrix.env }}
      DEPLOYER_LAMBDA_NAME: microapps-deployer-${{ matrix.env }}
      CDK_CONTEXT_ARGS: "--context @pwrdrvr/microapps:tableName=microapps-${{ matrix.env }} --context @pwrdrvr/microapps:s3BucketName=com.pwrdrvr.${{ matrix.env }}-microapps-${{ matrix.env }}"
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Get Domain Infix
        id: getDomainInfix
        run: |
          if [ "${{ matrix.env }}" == "prod" ]; then
            echo "::set-output name=domainInfix::"
          else
            echo "::set-output name=domainInfix::"${{ matrix.env }}.
          fi

      - name: Install Node Modules
        run: npm ci

      - name: Download Artifact - App
        uses: actions/download-artifact@v2
        with:
          name: app_zip
          path: packages/cdk-construct/lib/
      - name: Unzip Artifact - App
        working-directory: packages/cdk-construct/lib/
        run: unzip nextjs.zip

      # Prevent the static files from getting pulled into the Lambda
      - name: Remove Static Files from App Build
        working-directory: packages/cdk-construct/lib/
        run: |
          mkdir .static_files
          mv microapps-app-release/.next/static .static_files

      # Move to .mjs so it's treated as as module even though package.json will
      # have type=commonjs
      # - name: Move index.js to index.mjs
      #   working-directory: packages/cdk-construct/lib/microapps-app-release/
      #   run: |
      #     mv ./index.js ./index.mjs

      - name: Download Artifact - Story Book
        uses: actions/download-artifact@v2
        with:
          name: storybook_zip
          path: packages/app/
      - name: Unzip Artifact - App
        working-directory: packages/app/
        run: unzip storybook-static.zip

      - name: Download Artifact - Version.txt
        uses: actions/download-artifact@v2
        with:
          name: version-txt
      - run: echo PACKAGE_VERSION=$(cat version.txt) >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: microapps-app-${{ env.APP_NAME }}-build
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/builder-writeRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Preflight Check Version - App
        run: |
          npx microapps-publish preflight -a ${APP_NAME} -n ${PACKAGE_VERSION} -d ${DEPLOYER_LAMBDA_NAME}

      - name: Preflight Check Version - Story Book
        run: |
          npx microapps-publish preflight -a ${APP_NAME}-storybook -n ${PACKAGE_VERSION} -d ${DEPLOYER_LAMBDA_NAME}

      - name: Deploy CDK Stack - App
        run: npx cdk deploy ${CDK_CONTEXT_ARGS} --hotswap --require-approval never app

      - name: Publish to MicroApps - App
        run: |
          npx microapps-publish publish -a ${APP_NAME} -n ${PACKAGE_VERSION} -d ${DEPLOYER_LAMBDA_NAME} -l microapps-app-${APP_NAME}-${{ matrix.env }} -s packages/cdk-construct/lib/.static_files/static

      - name: Publish MicroApps - Story Book
        run: |
          npx microapps-publish publish-static -a ${APP_NAME}-storybook -n ${PACKAGE_VERSION} -d ${DEPLOYER_LAMBDA_NAME} -s packages/app/storybook-static -i index.html
