name: Cleanup Merged PR

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  workflow_dispatch:

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  NODE_ENV: prod
  APP_NAME: release
  APP_NAME_STORYBOOK: release-storybook
  DEPLOYER_LAMBDA_NAME: microapps-core-ghpublic-deployer-prod
  AWS_REGION: us-east-2

jobs:
  cleanup-pr:
    if: github.actor != 'dependabot[bot]'
    concurrency:
      group: pr-closed-${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    environment:
      name: ghpublic
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/configure-nodejs

      - name: Extract Current NPM Version
        run: |
          PACKAGE_VERSION_ORIG="$(node -p -e "require('./package.json').version")"
          echo "PACKAGE_VERSION=${PACKAGE_VERSION_ORIG}-pr.${PR_NUMBER}" >> "$GITHUB_ENV"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-session-name: microapps-app-${{ env.APP_NAME }}-build
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/builder-writeRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete App from MicroApps
        run: |
          pnpm exec microapps-publish delete -a "${APP_NAME}" -n "${PACKAGE_VERSION}" -d "${DEPLOYER_LAMBDA_NAME}"
          pnpm exec microapps-publish delete -a "${APP_NAME_STORYBOOK}" -n "${PACKAGE_VERSION}" -d "${DEPLOYER_LAMBDA_NAME}"

      - name: Destroy CDK Stack
        run: |
          aws cloudformation delete-stack --stack-name "microapps-app-${APP_NAME}-${NODE_ENV}-pr-${PR_NUMBER}"
          aws cloudformation wait stack-delete-complete --no-paginate --output text --stack-name "microapps-app-${APP_NAME}-${NODE_ENV}-pr-${PR_NUMBER}"
